# Identation
vueIndentScriptAndStyle = true

# Wrapping
embeddedLanguageFormatting = "auto"
htmlWhitespaceSensitivity = "css"
printWidth = 80
proseWrap = "always"
singleAttributePerLine = false

# Formating
arrowParens = "always"
bracketSameLine = false
bracketSpacing = true
jsxSingleQuote = false
quoteProps = "as-needed"
semi = false
singleQuote = false
trailingComma = "es5"

[[overrides]]
files = "*.md"

[overrides.options]
printWidth = 80
tabWidth = 2
